platform :ios, '5.0'
pod 'ZBarSDK'
pod 'BlocksKit'
pod 'AStarFinding', :git => 'git://github.com/IvanUshakov/AStarFinding.git'
pod 'KNMultiItemSelector', :git => 'git://github.com/IvanUshakov/KNMultiItemSelector.git'
